name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Swift ${{ matrix.platform }} on ${{ matrix.os }}
    runs-on: macos-latest

    strategy:
      matrix:
        platform:
          - platform=iPhone 16 Pro Max
          - platform=iPhone 16 Pro
        os: 
          - 17.4
          - 18.2

    steps:
    
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Install any dependencies
    - name: Install Dependencies
      run: swift package resolve

    # Run tests on ${{ matrix.platform }} with iOS ${{ matrix.os }}
    - name: Run Tests on ${{ matrix.platform }} (iOS ${{ matrix.os }})
      run: |
        xcodebuild test \
          -scheme 'AlamofireSwiftSoup' \
          -destination 'platform=iOS Simulator,name=${{ matrix.platform }},OS=${{ matrix.os }}'
